### ISSUE TITLE
Any reason for changing the syntax adding a space?

### ISSUE THREAD

**Issue by marcelklehr** [mrpandey/omnibang#4]
I'm wondering if there's a rationale for adding the space after the exclamation mark.

**Comment by mrpandey** [comment]
"!" serves as the keyword for omnibox (address bar of browser). This is how the browser knows that it has to pass the search term to the extension instead of going with default search. And, the keyword must be followed by space in order for this to work.

Also, I cannot associate multiple keywords like "!yt", "!mdn", "!ddg" with a single extension.

**Comment by marcelklehr** [comment]
Ah, I see. That's pretty clever actually, even if I have to change my habits :D
